version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/f8w2s7k7/iea2tech-frontend:latest
  build:
    commands:
      - docker build -t iea2tech-frontend:latest .
      - docker tag iea2tech-frontend:latest public.ecr.aws/f8w2s7k7/iea2tech-frontend:latest
  post_build:
    commands:
      - docker push public.ecr.aws/f8w2s7k7/iea2tech-frontend:latest
      - printf '[{"name":"iea2tech-frontend","imageUri":"%s"}]' public.ecr.aws/f8w2s7k7/iea2tech-frontend:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
